---
- name: install docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "{{ docker_compose_install_dir }}/docker-compose"

- name: make docker-compose executable
  file:
    path: "{{ docker_compose_install_dir }}/docker-compose"
    owner: root
    group: root
    mode: u+x
