---
- name: apt-key add
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ubuntu_distribution }} {{ ansible_distribution_release }} stable"
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - "docker service"
